#.travis.yml

language: node_js
node_js:
  - "8.9"

jobs:
    include:
      - stage: Dependencies
        script: npm install
      - stage: Linting
        script: npm run lint
      - stage: Unit Tests
        script: npm run test -- --browser=PhantomJS --watch=false
      - stage: AOT Build
        script: npm run build -- --prod --aot
